apiVersion: v1
kind: Service
metadata:
    name: camunda-service
    namespace: camunda
spec:
  ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080 
        name: http     
  selector:
      name: camunda-deployment
  type: LoadBalancer